Geometry_Engine: Added InterpolationOrder to constructor for TaperedProfile and function to determine shape of TaperedProfile if constant
BHoM/BHoM_Engine pull request #1980
Opened 2020-09-09 20:48 UTC by peterjamesnugent

### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/992
   
### Issues addressed by this PR

Closes #1978

### Test files

### Changelog

### Additional comments

To be closed in Sprint 1 of 4.0 Milestone.

2020-10-05 21:41 UTC, peterjamesnugent commented
@IsakNaslundBh as discussed the `positions` returned from `MapTaperedProfile()` are relative to the `TaperedProfile` they have been derived from. This will mean that any further interpolation will be correct. 

I've also added a `MapPositionDomain` function that allows a domain to be mapped to `[0,1]` for when it's being pushed in to an FEA software.

2020-10-09 07:50 UTC, IsakNaslundBh requested changes
Some first review of just the code here on github. Some pre-migration of stuff out of geometry_Engine (new stuff added) and some general smaller compliance things.

2020-10-09 07:50 UTC, IsakNaslundBh commented on Geometry_Engine/Compute/InterpolateProfile.cs
> +namespace BH.Engine.Geometry
Would move this whole class to spatial_Engine and namespace. We are planning to migrate all profiles over there early this milestone, preferably next sprint, and would like to have as little versioning as possible! :)

2020-10-09 07:50 UTC, IsakNaslundBh commented on Geometry_Engine/Compute/InterpolateProfile.cs
> +        public static IProfile InterpolateProfile(IProfile startProfile, IProfile endProfile, double parameter, int interpolationOrder)
Should be an interface method. Would also move this to the bottom of the file under a 

```
        /***************************************************/
        /**** Public Methods - Interfaces               ****/
        /***************************************************/
```

```suggestion
        public static IProfile IInterpolateProfile(IProfile startProfile, IProfile endProfile, double parameter, int interpolationOrder)
```


Should also add a private fallback method accepting two `IProfile`s (same signature that this currently have) raising an error and returning null.

2020-10-09 07:50 UTC, IsakNaslundBh commented on Geometry_Engine/Compute/InterpolateProfile.cs
> +        private static AngleProfile InterpolateProfile(AngleProfile startProfile, AngleProfile endProfile, double parameter, int interpolationOrder)
Should be public to follow general BHoM standard. Same for all the other methods.

Understand why you have done it like this from the side of the UI, but think we should follow what we are doing elsewhere atm.

2020-10-09 07:50 UTC, IsakNaslundBh commented on Geometry_Engine/Modify/MApPositionDomain.cs
> +namespace BH.Engine.Geometry
Same as above, lets put this in Spatial_Engine straight away.

2020-10-09 07:50 UTC, IsakNaslundBh commented on Structure_Engine/Compute/MapTaperedProfile.cs
> +        public static List<Bar> IMapTaperedSection(List<Bar> bars, ISectionProperty section)
Would put this at the bottom of the file under a

```
        /***************************************************/
        /**** Public Methods - Interfaces               ****/
        /***************************************************/
```

2020-10-09 07:50 UTC, IsakNaslundBh commented on Structure_Engine/Compute/MapTaperedProfile.cs
> +        public static List<Bar> MapTaperedSection(List<Bar> bars, ISectionProperty section)
Would make this private as it is kind of a fallback.

2020-10-09 07:50 UTC, IsakNaslundBh commented on Structure_Engine/Compute/MapTaperedProfile.cs
> +                        }
We should not use try-catch as a filter mechanism. Exceptions should only be used for real exceptions. They are significantly slower than doing the check needed ourselfs. Reading the comment of the code, I think something along the lines the following could work:


```suggestion
                        int interpolationIndex = Math.Min(i, newInterpolationOrders.Count-1);
                        int newInterpolationOrder = newInterpolationOrders[interpolationIndex];

```

Good to add some comment as well as to how the `i` relates to the list of interpolation orders. Assume you have one less interpolation order than number of profiles?

2020-10-14 14:16 UTC, IsakNaslundBh requested changes
Wrong version in previous method attribute. Should be the current version we are working ok :)

Not sure if there are more that I missed

2020-10-14 14:16 UTC, IsakNaslundBh commented on Geometry_Engine/Create/ShapeProfile.cs
> +        [PreviousVersion("3.3", "BH.Engine.Geometry.Create.TaperedProfile(System.Collections.Generic.List<System.Decimal>, System.Collections.Generic.List<BH.oM.Geometry.ShapeProfiles.IProfile>)")]
```suggestion
        [PreviousVersion("4.0", "BH.Engine.Geometry.Create.TaperedProfile(System.Collections.Generic.List<System.Decimal>, System.Collections.Generic.List<BH.oM.Geometry.ShapeProfiles.IProfile>)")]
```

2020-10-14 14:16 UTC, IsakNaslundBh commented on Geometry_Engine/Create/ShapeProfile.cs
> +        [PreviousVersion("3.3", "BH.Engine.Geometry.Create.TaperedProfile(BH.oM.Geometry.ShapeProfiles.IProfile, BH.oM.Geometry.ShapeProfiles.IProfile)")]
```suggestion
        [PreviousVersion("4.0", "BH.Engine.Geometry.Create.TaperedProfile(BH.oM.Geometry.ShapeProfiles.IProfile, BH.oM.Geometry.ShapeProfiles.IProfile)")]
```

2020-10-14 15:50 UTC, IsakNaslundBh approved these changes
Seem to be working fine now! Great to get the interpolate methods added!

2020-10-15 07:56 UTC, IsakNaslundBh commented
/azp run BHoM_Engine.CheckInstaller

2020-10-15 08:39 UTC, merged