Physical_Engine: BulkMaterials Volume Query
BHoM/BHoM_Engine pull request #2113
Opened 2020-10-29 20:23 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #2112 

### Test files

### Changelog

### Additional comments

2020-11-09 08:50 UTC, IsakNaslundBh requested changes
Tweaks to the material composition method.

2020-11-09 08:50 UTC, IsakNaslundBh commented on Physical_Engine/Query/MaterialComposition.cs
> +            return Matter.Create.MaterialComposition(bulkMaterial.MaterialComposition().Materials, bulkMaterial.MaterialComposition().Ratios);
Can just return the property here? (also think the current implementation will lead to stack-overflow if I am not missing something).

Might want to keep the warning as well, if usefull.

```suggestion
            return bulkMaterial.MaterialComposition;
```

If you want to create a new material composition, should at least change to:

```suggestion
            if (bulkMaterial.MaterialComposition == null)
            {
                Engine.Reflection.Compute.RecordError("The BulkMaterial MaterialComposition could not be calculated as no Materials have been assigned.");
                return null;
            }
            return Matter.Create.MaterialComposition(bulkMaterial.MaterialComposition.Materials, bulkMaterial.MaterialComposition.Ratios);
```

To avoid the stack overflow.

2020-11-09 13:21 UTC, michaelhoehn commented on Physical_Engine/Query/MaterialComposition.cs
> +            return Matter.Create.MaterialComposition(bulkMaterial.MaterialComposition().Materials, bulkMaterial.MaterialComposition().Ratios);
Thanks @IsakNaslundBh, indeed the last commit led to stack-overflow. I've changed to simply use the properties to work as expected.

2020-11-10 16:28 UTC, michaelhoehn commented
Closing this draft PR as this is dependant and needed to be re-branched. I initially intended for the PRs to take place in sequence, but find them easier to pair together.

2020-11-10 16:28 UTC, closed without merging