Spatial_Engine: Add Query.IsNearLevel() method
BHoM/BHoM_Engine pull request #2123
Opened 2020-11-04 09:57 UTC by IsakLarbornBH

### Issues addressed by this PR

Closes #2054 

Adds Query.IsNearLevel() method to Spatial_Engine. This method accepts an IElement, a Level, and a double maxDistance as input, and tests the IElement for proximity to the Level, returning true if the distance is lower than or equal to maxDistance.

### Test files

[IsNearLevel-Test.zip](https://github.com/BHoM/BHoM_Engine/files/5486948/IsNearLevel-Test.zip)

### Changelog
`Query.IsNearLevel()` Query method added in the `Spatial_Engine` for `IElement` class

### Additional comments
While this method is heavily based on IsNearGrid(), creating it was not as straightforward, as there are no existing methods to measure the distance to a Level or even a Plane as far as I could tell. I tried to find a reasonably simple approach using the methods that were available, but I would like your feedback and suggestions if you have any.

2020-11-04 16:11 UTC, FraserGreenroyd commented
@BHoMBot check documentation compliance

2020-11-04 16:11 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2020-11-04 16:11 UTC, FraserGreenroyd commented
@BHoMBot check project compliance

2020-11-04 16:12 UTC, FraserGreenroyd commented
@BHoMBot check copyright compliance

2020-11-09 10:58 UTC, IsakNaslundBh requested changes
Think the code makes sense, and seem to be working.

Some comments on the descriptions, commented on IElement0D, but hold true for the others as well.

Especially, the geometry is not projected (would not make sense to check against levels :) ) and it is not a level line, but a level elevation.

Could also add a backup method, something like:

```
        private static bool IsNearLevel(this IElement element, Level level, double maxDistance)
        {
            Reflection.Compute.RecordError($"IsNearLevel is not implemented for IElements of type: {element.GetType().Name}.");
            return false;
        }

```

for a case where a new IElement type is added, but no support added to it for this particular method.

If so, but it at the bottom of the file. Could have a look at the `Length` method in Geometry_Engine for example.

2020-11-09 10:58 UTC, IsakNaslundBh commented on Spatial_Engine/Query/IsNearLevel.cs
> +        [Description("Checks if the geometrical representation of an IElement0D, projected onto the XY Plane, is within a set distance from a level line.")]
Description needs update
```suggestion
        [Description("Checks if the geometrical representation of an IElement0D is within a set distance from a level elevation.")]
```

2020-11-09 10:58 UTC, IsakNaslundBh commented on Spatial_Engine/Query/IsNearLevel.cs
> +        [Output("isNearLevel", "A boolean which is true if the geometrical representation of the IElement0D is within a set distance from the level line.")]
```suggestion
        [Output("isNearLevel", "A boolean which is true if the geometrical representation of the IElement0D is within a set distance from the level elevation.")]
```

2020-11-09 12:48 UTC, IsakLarbornBH commented
> Some comments on the descriptions, commented on IElement0D, but hold true for the others as well.

Ah, that's embarrassing. If you haven't figured that out, I did a find/replace on IsNearGrid, then forgot to actually check if the descriptions made sense since they looked fine at a glance. At least that should be a quick fix.

Adding a backup method makes sense, should IsNearGrid have one as well then?

2020-11-09 13:07 UTC, IsakNaslundBh commented
> > Some comments on the descriptions, commented on IElement0D, but hold true for the others as well.
> 
> Ah, that's embarrassing. 

Do not feel embarrassed! It is a minor copy paste mistake which all in the dev team have done many times. (I am confident you will have a chance to make similar remarks on some things I have written in the future 😃 )

> Adding a backup method makes sense, should IsNearGrid have one as well then?

Yeah, if you do not mind, please add one in for the IsNearGrid method as well!

2020-11-09 14:00 UTC, FraserGreenroyd commented
> > Ah, that's embarrassing.
>
> Do not feel embarrassed! It is a minor copy paste mistake which all in the dev team have done many times. (I am confident you will have a chance to make similar remarks on some things I have written in the future 😃 )

Kopier, klistra in is the bane of my life!

Although, if you're interested in seeing how it can help, I recommend this book to most people :wink:

![image](https://user-images.githubusercontent.com/18049174/98550264-caa0ba00-2293-11eb-95c1-8e9c73140e2b.png)

2020-11-09 16:25 UTC, IsakLarbornBH commented
> Although, if you're interested in seeing how it can help, I recommend this book to most people 😉

I am familiar with that book, it taught me everything I know about coding :)

I've made the requested changes (and a couple more) so I'm ready for round 2.

2020-11-10 08:33 UTC, IsakNaslundBh approved these changes
now LGTM

2020-11-10 08:34 UTC, IsakNaslundBh commented
/azp run BHoM_Engine.CheckInstaller

2020-11-10 08:34 UTC, IsakNaslundBh commented
@BHoMBot check code compliance

2020-11-10 08:34 UTC, IsakNaslundBh commented
@BHoMBot check copyright compliance

2020-11-10 08:34 UTC, IsakNaslundBh commented
@BHoMBot check project compliance

2020-11-10 08:35 UTC, IsakNaslundBh commented
@BHoMBot check documentation compliance

2020-11-10 09:35 UTC, merged