MEP_Engine: Added support to CameraDevice objects
BHoM/BHoM_Engine pull request #2152
Opened 2020-11-13 14:12 UTC by tiagogrossi

### NOTE: Depends on 
[BHoM/BHoM#1085](https://github.com/BHoM/BHoM/pull/1085)

   
### Issues addressed by this PR

Closes #2147 

Added support for Camera device object

### Test files
Test file [here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/MEP_oM/Issue1078-Create%20definition%20for%20Camera%20devices/MEP_oM-Issue1078-Create%20definition%20for%20Camera%20devices.gh?csf=1&web=1&e=CERKJ1).

### Changelog
Added `BH.Engine.MEP.Compute.Error`
Modified `BH.Engine.MEP.Query.Geometry`
Modified `BH.Engine.MEP.Query.Centreline`

2020-11-13 14:16 UTC, tiagogrossi commented
@FraserGreenroyd thanks for the advice on the geometry extraction for this one. After a chat with Isak I felt that `IImmutable` isn't suitable for this object because it has to be flexible. The geometry is driven by the first 3 properties of the object, that can change freely, so I'm not giving the option for the user to set the geometry randomly. Does that makes sense? Suggestion?

2020-11-15 12:02 UTC, FraserGreenroyd requested changes

2020-11-15 12:02 UTC, FraserGreenroyd commented on MEP_Engine/Compute/Error.cs
> +        }
I don't like this kind of approach to this, and this isn't even being used anywhere in the rest of the code. Please delete it.

2020-11-15 12:02 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-11-17 18:29 UTC, enarhi commented
Migrated to Security_Engine namespace as per https://github.com/BHoM/BHoM/pull/1091

2020-11-17 21:44 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-11-17 21:45 UTC, FraserGreenroyd commented
/azp run BHoM_Engine.CheckInstaller

2020-11-17 22:07 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-11-17 22:08 UTC, FraserGreenroyd commented
@BHoMBot fix project file ref. 1414955338

2020-11-17 22:09 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2020-11-17 22:09 UTC, FraserGreenroyd commented
/azp run BHoM_Engine.CheckInstaller

2020-11-17 22:22 UTC, FraserGreenroyd approved these changes
LGTM, thanks @enarhi for picking it up and moving to Security Engine - merging to unblock you and allowing you to continue on with @tiagogrossi :smile:

2020-11-17 22:22 UTC, merged