Reflection_Engine: Add support for new fragments attributes
BHoM/BHoM_Engine pull request #2164
Opened 2020-11-17 07:19 UTC by adecler

### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1093

   
### Issues addressed by this PR
See https://github.com/BHoM/BHoM/pull/1093 for details

2020-11-17 09:46 UTC, FraserGreenroyd requested changes

2020-11-17 09:46 UTC, FraserGreenroyd commented on BHoM_Engine/Modify/AddFragment.cs
> +                    Engine.Reflection.Compute.RecordWarning("There is already a fragment of type " + restriction + " on this object. \nThe Fragment will still be aded but consider reviewing this task
```suggestion
                    Engine.Reflection.Compute.RecordWarning("There is already a fragment of type " + restriction + " on this object. \nThe Fragment will still be added but consider reviewing this task as fragments of that type are supposed to be unique.");
```

2020-12-08 07:16 UTC, adecler commented
This PR hasn't been reviewed nor merged in 3 weeks and is now past the deadline for feature PRs on this milestone. 
Since it doesn't seem to be as urgent as we initially thought, I will park this for now

2021-01-13 15:34 UTC, IsakNaslundBh approved these changes
Had to rebase and forcepush to resolve conflicts and get this to merge with master, hope you are ok with that @adecler .

I am generally happy with the functionality of this.

Would be good if we had some mechanism for replacing a unique attribute, but can come in subsequent PRs. This is, if I have IMaterialProperties and unique, and have a Steel on an object and try to add a Concrete. Would for this case be good if we had a mechanism for replacing the Steel with the new Concrete.

This can all be resolved later though, as this is a great first step!

Approving, but as I made the last commits by the force push, would be good if @FraserGreenroyd had a chance to look through.

2021-01-13 15:36 UTC, IsakNaslundBh commented
@BHoM check compliance

2021-01-13 15:38 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2021-01-13 17:18 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2021-01-13 20:28 UTC, FraserGreenroyd requested changes
This looks good to me, just blocking till oM PR is ready to avoid accidental merge! Can be dismissed or changed to approval once oM is ready to go :smile:

2021-01-13 20:28 UTC, FraserGreenroyd commented on BHoM_Engine/BHoM_Engine.csproj
> +	<Compile Include="Objects\EqualityComparers\HashComparer.cs" />
Is it just me, or are these indented more?

2021-01-14 02:55 UTC, adecler commented
/azp run BHoM_Engine.CheckInstaller

2021-01-14 02:55 UTC, adecler commented
@BHoMBot check copyright

2021-01-14 08:11 UTC, FraserGreenroyd commented
@BHoMBot check code compliance

2021-01-14 08:23 UTC, FraserGreenroyd approved these changes
This LGTM now :smile:

2021-01-14 08:49 UTC, merged