Spatial_Engine: Query Thickness of IProfiles
BHoM/BHoM_Engine pull request #2172
Opened 2020-11-17 23:22 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #2171 

### Test files

[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Spatial_Engine/Issues/Spatial_Engine-%232171-IProfileThicknessQuery/IProfileThickness.gh?csf=1&web=1&e=ozLBf5)

### Changelog

### Additional comments

2020-11-18 08:35 UTC, IsakNaslundBh requested changes
For this to feel a bit more useful from the side of the UI, I think it should be expanded to cover all profiles, and/or needs a fallback method!

2020-11-18 09:02 UTC, FraserGreenroyd requested changes
Definitely needs a fall back method echoing @IsakNaslundBh regardless - but would also agree it would be good to cover all profiles at this point.

2020-11-18 20:11 UTC, michaelhoehn commented
Thanks @IsakNaslundBh and @FraserGreenroyd. I've added support for each ShapeProfile that has a Thickness property. This particular method would really only support three types: Box, Tube and Kite. The fallback method error message should reflect which profile types aren't supported. 

I prototyped a multi-output method for the others but felt that may constitute a separate method to cover multiple thicknesses.

2020-11-20 22:56 UTC, michaelhoehn commented
/azp run BHoM_Engine.CheckInstaller

2020-11-22 13:50 UTC, FraserGreenroyd requested changes
Documentation could do with improving entirely but as a starting point it's ok - just needs some grammar changes, see suggestions.

Otherwise I feel this is appropriate following our conversation where the other Profiles have multiple thickness attributes, and choosing which one to show may be misleading, or summing them may also be misleading. @IsakNaslundBh what would be your thoughts on that given you implemented most of the profile I suspect?

2020-11-22 13:50 UTC, FraserGreenroyd commented on Spatial_Engine/Query/Thickness.cs
> +        [Input("boxProfile", "The boxProfile to query.")]
```suggestion
        [Input("boxProfile", "The BoxProfile to query.")]
```

2020-11-22 13:50 UTC, FraserGreenroyd commented on Spatial_Engine/Query/Thickness.cs
> +        [Description("Returns the thickness of a boxProfile.")]
```suggestion
        [Description("Returns the thickness of a BoxProfile.")]
```

2020-11-22 13:50 UTC, FraserGreenroyd commented on Spatial_Engine/Query/Thickness.cs
> +        [Output("thickness", "Thickness of the boxProfile.", typeof(Length))]
```suggestion
        [Output("thickness", "Thickness of the BoxProfile.", typeof(Length))]
```

2020-11-22 13:50 UTC, FraserGreenroyd commented on Spatial_Engine/Query/Thickness.cs
> +        [Output("thickness", "Thickness of the kiteProfile.", typeof(Length))]
```suggestion
        [Description("Returns the thickness of a KiteProfile.")]
        [Input("kiteProfile", "The KiteProfile to query.")]
        [Output("thickness", "Thickness of the KiteProfile.", typeof(Length))]
```

2020-11-22 13:50 UTC, FraserGreenroyd commented on Spatial_Engine/Query/Thickness.cs
> +        [Output("thickness", "Thickness of the tubeProfile.", typeof(Length))]
```suggestion
        [Description("Returns the thickness of a TubeProfile.")]
        [Input("tubeProfile", "The TubeProfile to query.")]
        [Output("thickness", "Thickness of the TubeProfile.", typeof(Length))]
```

2021-01-06 12:57 UTC, FraserGreenroyd requested changes

2021-01-06 12:57 UTC, FraserGreenroyd commented on Spatial_Engine/Query/Thickness.cs
> + * Copyright (c) 2015 - 2020, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2021, the respective contributors. All rights reserved.
```

2021-01-06 12:57 UTC, FraserGreenroyd commented
@BHoMBot check copyright compliance

2021-01-06 12:58 UTC, FraserGreenroyd commented
/azp run BHoM_Engine.CheckInstaller

2021-01-06 14:07 UTC, FraserGreenroyd approved these changes
This LGTM now, thanks @michaelhoehn

2021-01-06 14:08 UTC, merged