Reflection_Engine: Fix SetProperty of CustomData
BHoM/BHoM_Engine pull request #2281
Opened 2021-01-26 03:57 UTC by adecler

### Issues addressed by this PR

Closes #362

Changing a value stored in CustomData is now possible even if the corresponding key already exists

### Test files
See issue

### Changelog

### Additional comments

2021-01-26 03:57 UTC, adecler commented
@BHoMBot check copyright

2021-01-26 10:01 UTC, FraserGreenroyd commented
@BHoMBot check copyright compliance

2021-01-26 10:08 UTC, FraserGreenroyd requested changes
Minor grammar suggestions on the user messages, otherwise LGTM.

2021-01-26 10:08 UTC, FraserGreenroyd commented on Reflection_Engine/Modify/SetPropertyValue.cs
> +                Compute.RecordWarning("The objects does not contain any property with the name " + propName + ". The value is being set as a fragment.");
```suggestion
                Compute.RecordWarning("The object does not contain any property with the name " + propName + ". The value is being set as a fragment.");
```

Or

```suggestion
                Compute.RecordWarning("The objects do not contain any property with the name " + propName + ". The value is being set as a fragment.");
```

`objects does` doesn't read quite right to me, one of them should be singular but not sure what the rest of the method is doing so suggesting both options. Looks like the method takes in a single object so the first one might be more appropriate?

2021-01-26 10:08 UTC, FraserGreenroyd commented on Reflection_Engine/Modify/SetPropertyValue.cs
> +                Compute.RecordWarning("The objects does not contain any property with the name " + propName + ". The value is being set as custom data.");
```suggestion
                Compute.RecordWarning("The object does not contain any property with the name " + propName + ". The value is being set as custom data.");
```

Or

```suggestion
                Compute.RecordWarning("The objects do not contain any property with the name " + propName + ". The value is being set as custom data.");
```

2021-01-27 11:20 UTC, FraserGreenroyd approved these changes
Wording LGTM now, will leave @pawelbaran to do a final functionality review has he raised the issue to be fixed :smile:

2021-01-27 11:41 UTC, pawelbaran approved these changes
LGTM

Btw, the issue was originally raised in the BHoM_UI, I have transferred it to BHoM_Engine and updated numbers/links/folders. Should be ready to merge now 👍

2021-01-27 11:41 UTC, pawelbaran commented
@BHoMBot check installer

2021-01-27 11:58 UTC, pawelbaran commented
/azp run BHoM_Engine.CheckInstaller

2021-01-27 11:58 UTC, pawelbaran commented
@BHoMBot check copyright

2021-01-27 12:11 UTC, merged