Methods to flatten and split the trees made of nested ILogicalRequests added
BHoM/BHoM_Engine pull request #2298
Opened 2021-02-04 18:15 UTC by pawelbaran

### Issues addressed by this PR

Closes #2296
Closes #2297

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FData%5FEngine&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4). I had hard times coming up with automated way of generating and testing the data, therefore hand-made trees are provided for visual inspection. Happy to improve the tests if a smarter way is suggested.

### Changelog

- added method to simplify trees made of nested `ILogicalRequests`
- added method to split trees made of nested `ILogicalRequests` in a way that ensures that each resultant tree contains max. one `IRequest` of given type and all resultant trees combined constitute same request as the original tree
- added a method to check whether a tree created by a set of nested `ILogicalRequests` contains two or more `IRequests` of given type that can conflict (fall into a logical and statement)

### Additional comments

The functionality can look a bit abstract without a use case - this will follow in Revit_Toolkit, so please focus on the correctness of the methods for now 😃 

I was convinced the problem will be rather easy to solve (rather simple tree traversal), but it turned to be more tricky than it looked. The code got a bit convoluted, but it works (I hope 🙈), happy to accept suggestions on potential simplifications.

2021-02-11 11:22 UTC, alelom submitted a review, later dismissed
The code looks good and works. There is some overlap with some work we are doing in the combining of Conditions in CIH, and we discussed some refactoring of the Requests to be done in the future, and some work of this PR may be part of it then.

2021-02-11 13:20 UTC, pawelbaran commented
@BHoMBot check copyright

2021-02-11 13:21 UTC, pawelbaran commented
/azp run BHoM_Engine.CheckInstaller

2021-02-11 15:43 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2021-02-11 15:51 UTC, pawelbaran commented
@FraserGreenroyd could you have a look at this?
- branch name is just fine (did @BHoMBot go mad?)
- I would opt for keeping the private `enum` inside the class - alternatively can change it to an integer (in the end the values of the enumeration represent 0, 1 and more occurences), but this will make the code less readable

2021-02-13 00:52 UTC, FraserGreenroyd commented
> * branch name is just fine (did @BHoMBot go mad?)

See previous reply on the linked PR regarding this.

> * I would opt for keeping the private `enum` inside the class - alternatively can change it to an integer (in the end the values of the enumeration represent 0, 1 and more occurences), but this will make the code less readable

I disagree, this is heavily against BHoM guidelines of one class per file and making objects/methods easy to find when reflected from a UI. If there is something which does not need to be within a UI, but is required to make an engine method work, that is where the `Objects` folder comes in within the Engine. I believe Structure_Engine has an example of this in use that could be replicated here and have the enum moved to its own file there :smile:

2021-02-13 00:52 UTC, FraserGreenroyd requested changes
PR title needs to include engine changed.

Compliance needs resolving, see previous comment.

2021-02-15 09:19 UTC, pawelbaran commented
> > * I would opt for keeping the private `enum` inside the class - alternatively can change it to an integer (in the end the values of the enumeration represent 0, 1 and more occurences), but this will make the code less readable
> 
> I disagree, this is heavily against BHoM guidelines of one class per file and making objects/methods easy to find when reflected from a UI. If there is something which does not need to be within a UI, but is required to make an engine method work, that is where the `Objects` folder comes in within the Engine. I believe Structure_Engine has an example of this in use that could be replicated here and have the enum moved to its own file there 😄

But `enum` is not a class? On top of that, it is `private` and makes absolutely zero sense to be reused anywhere else, being very problem-specific, so putting it in _Objects_ is pointless too. Therefore, I see two options here:
a) accept it as an edge case and update the compliance rules to accept it, when time allows (IMO that would be fully valid)
b) change the enum into an `int`, make the code less readable but keep the compliance happy

As usual in such cases, my opinion is that compliance checks should be for developers, not developers for compliance checks @FraserGreenroyd.

2021-02-15 11:00 UTC, FraserGreenroyd commented
> But `enum` is not a class? On top of that, it is `private` and makes absolutely zero sense to be reused anywhere else, being very problem-specific, so putting it in _Objects_ is pointless too.

`enum` is a special class representing constants. In these terms, it is treated in the same way as `interface`. If it is not intended to be reused anywhere, then the `Objects` folder is ideal for it. It allows the class to have its own file which avoids hiding it/obfuscating it for future maintainers, as is BHoM's philosophy.

> a) accept it as an edge case and update the compliance rules to accept it, when time allows (IMO that would be fully valid)

This is not an acceptable edge case so I would not be prepared to update the rules that check it at this stage unless there is additional evidence to this being necessary and beneficial.

> b) change the enum into an `int`, make the code less readable but keep the compliance happy

I think the move to `Objects` is cleaner, but changing to an `int` is acceptable but that is just a box-ticking at that point. The wider philosophy should be considered for the decision.

> As usual in such cases, my opinion is that compliance checks should be for developers, not developers for compliance checks @FraserGreenroyd.

It's important to remember the guidelines we have that BHoMBot enforces are to help keep the code true to BHoM's core principles of being accessible and maintainable by those without heavy coding backgrounds. Hiding classes (enums, interfaces) within classes begins to break down that ease of access philosophy. There are concepts of software development that BHoM has actively chosen to avoid for various reasons. That said, even in traditional software development, I don't know of many places that would enjoy the practice of hiding things within things, even in software houses most style guides will say to keep classes separate unless completely unavoidable :smile:

2021-02-15 11:14 UTC, pawelbaran commented
> > But `enum` is not a class? On top of that, it is `private` and makes absolutely zero sense to be reused anywhere else, being very problem-specific, so putting it in _Objects_ is pointless too.
> 
> `enum` is a special class representing constants. In these terms, it is treated in the same way as `interface`. If it is not intended to be reused anywhere, then the `Objects` folder is ideal for it. It allows the class to have its own file which avoids hiding it/obfuscating it for future maintainers, as is BHoM's philosophy.

That is your opinion I would argue with. First of all, `enum` is a value type, so rather not too close to types declared using standard classes or interfaces. As far as I know, _Objects_ folder is used to store Engine-specific objects, not enums - to me, a private `enum` would look there at least weird and would not improve clarity at all. So again, please do consider and respect the fact that others may have different opinions on things that were never discussed in detail and verified. We have been there with other compliance issues before, @IsakNaslundBh remembers for sure.

> 
> > a) accept it as an edge case and update the compliance rules to accept it, when time allows (IMO that would be fully valid)
> 
> This is not an acceptable edge case so I would not be prepared to update the rules that check it at this stage unless there is additional evidence to this being necessary and beneficial.

Please see the reply above.

> 
> > b) change the enum into an `int`, make the code less readable but keep the compliance happy
> 
> I think the move to `Objects` is cleaner, but changing to an `int` is acceptable but that is just a box-ticking at that point. The wider philosophy should be considered for the decision.

That is what will happen, credits to you 😉

2021-02-15 11:32 UTC, pawelbaran commented
I have pushed the change, not too much of a disaster after renaming the method param @FraserGreenroyd - a well-named `int` looks like a fair compromise in this case.

@alelom could you please re-review? Please note the scope of changes made in my commit, likely not much re-testing should be needed. Thanks!

2021-02-15 11:32 UTC, pawelbaran commented
@BHoMBot check compliance

2021-02-15 11:39 UTC, pawelbaran commented
@BHoMBot check installer

2021-02-15 11:46 UTC, pawelbaran commented
/azp run BHoM_Engine.CheckInstaller

2021-02-15 15:23 UTC, alelom approved these changes
re-reviewing, LGTM.

2021-02-15 15:36 UTC, FraserGreenroyd approved these changes
All happy now, thanks @pawelbaran :smile:

2021-02-15 15:36 UTC, merged