ExtensionMethodToCall isolated from RunExtensionMethod
BHoM/BHoM_Engine pull request #2331
Opened 2021-02-19 18:33 UTC by pawelbaran

### Issues addressed by this PR

Closes #2328

### Test files

On [SharePoint]() - it only proves that the mechanism used up to date still works - the benefits coming from this PR will be tested more explicitly in #2321.

### Changelog

- `ExtensionMethodToCall` method isolated from `RunExtensionMethod`

### Additional comments

What I do not like about the solution proposed in this PR is the fact that in case of execution failure the error message is missing the information about the method name. However, `Func<object[], object>` does not carry it any more, and StackOverflow says it would need to be wrapped into `Expression<T>`. Not sure if that is worth the extra complexity added to the code - happy to hear others' opinion on that.

2021-02-20 04:07 UTC, adecler commented
> What I do not like about the solution proposed in this PR is the fact that in case of execution failure the error message is missing the information about the method name. However, `Func<object[], object>` does not carry it any more, and StackOverflow says it would need to be wrapped into `Expression<T>`. Not sure if that is worth the extra complexity added to the code - happy to hear others' opinion on that.

Why not having your `GetExtensionMethod` returning a MethodInfo instead ? It could just store a dictionary of `ConcurrentDictionary<Tuple<Type, string>, MethodInfo>`. And then, you have your `RunExtensionMethod` storing a `ConcurrentDictionary<MethodInfo, Func<object[], object>>` for those methods that have already been compiled. At this point, it could even be called just `RunMethod` as it has nothing to do with extensions methods anymore.

2021-02-22 00:58 UTC, FraserGreenroyd reviewed
PR title needs to specify which engine is being modified please :smile:

2021-02-22 19:19 UTC, pawelbaran commented
@BHoMBot check compliance

2021-02-22 19:20 UTC, pawelbaran commented
/azp run BHoM_Engine.CheckInstaller

2021-02-22 19:20 UTC, pawelbaran commented
@BHoMBot check installer

2021-02-22 19:23 UTC, pawelbaran commented
@BHoMBot check core

2021-02-24 02:36 UTC, adecler approved these changes
Looks good to me. Now it's just a question of making the bot happy 😄

2021-02-24 02:38 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 1955310848

2021-02-24 03:36 UTC, adecler commented
@FraserGreenroyd , `Query` methods should always start with a `this` on the first argument. I don't think we should ignore that.

2021-02-24 03:38 UTC, adecler requested changes
All good. Just need to make the `Query` methods compliant

2021-02-24 03:38 UTC, adecler commented on Reflection_Engine/Query/ExtensionMethodToCall.cs
> +        public static MethodInfo ExtensionMethodToCall(object target, string methodName)
```suggestion
        public static MethodInfo ExtensionMethodToCall(this object target, string methodName)
```

2021-02-24 03:38 UTC, adecler commented on Reflection_Engine/Query/ExtensionMethodToCall.cs
> +        public static MethodInfo ExtensionMethodToCall(object target, string methodName, object[] parameters)
```suggestion
        public static MethodInfo ExtensionMethodToCall(this object target, string methodName, object[] parameters)
```

2021-02-24 09:23 UTC, pawelbaran commented
@BHoMBot check compliance

2021-02-24 09:32 UTC, adecler approved these changes

2021-02-24 09:34 UTC, pawelbaran commented
@BHoMBot check core

2021-02-24 09:35 UTC, pawelbaran commented
/azp run BHoM_Engine.CheckInstaller

2021-02-24 09:36 UTC, pawelbaran commented
@BHoMBot check installer

2021-02-24 11:09 UTC, merged