Geometry_Engine: Infinite loop removed from Split in case of overlapping cutting lines
BHoM/BHoM_Engine pull request #2407
Opened 2021-03-18 17:37 UTC by pawelbaran

### Issues addressed by this PR

Closes #2406

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232406%2DStackOverflowOnSplit%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine)

### Changelog

- Infinite loop removed from `BH.Engine.Geometry.Compute.Split` in case of overlapping cutting lines

### Additional comments

@FraserGreenroyd you are the originator so happy to get your review on it.

2021-03-22 20:40 UTC, michaelhoehn reviewed
I don't have any issues with the code other than a singular finding that may just be worth a mention here for consideration. I set up a simple test that I ran for the original PR approval. It's worth noting that the splitting and sorting algorthim has been adjusted upon method completion. The first GIF is the original test showing a consistent radial sorting vs the default GH method. This highlights an embedded efficiency gained with the BHoM method over the GH method (however I do believe compute time is a bit higher in the BHoM method). 

![BHoMSplit](https://user-images.githubusercontent.com/54593392/112055349-1a8a6a00-8b2d-11eb-9104-a8eb217eab5d.gif)

The second gif is this PR, resulting in a blended mix of the two methods essentially. I haven't run any comparison as far as compute time performance but was happy with the functionality, given that we currently don't have a solid use-case for requiring a radial sort for any existing workflow (that I know of). 

![Split_StackOverflowFix](https://user-images.githubusercontent.com/54593392/112055355-1eb68780-8b2d-11eb-883d-9c244fbfec7c.gif)

So as noted... I'm happy to approve as long as the proposed changes are noted and acknowledged, ideally by the original method creator or @FraserGreenroyd in this instance.

2021-03-22 22:10 UTC, michaelhoehn commented
@pawelbaran Here's the [test script](https://burohappold-my.sharepoint.com/:u:/r/personal/michael_hoehn_burohappold_com/Documents/Documents/0_Work/1_GH%20Scripts/0_Hoehn-TK/%232406-StackOverflowOnSplit-MH.gh?csf=1&web=1&e=DTBzg5) with that study.

2021-03-23 14:15 UTC, pawelbaran commented
Thanks @michaelhoehn for the thorough review. However, I have just compared the results generated by your test on both `master` as well as this branch (I have internalised them and added at the end of your script). They seem to be the same, so I am not sure how did you end up with the differences highlighted in your previous comments 🙈

2021-03-23 14:56 UTC, michaelhoehn commented
@pawelbaran hmm interesting. Upon further testing this PR compared to the master branch, I can confirm that this PR does fix the need to cull duplicate cutting lines and the need to combine both the perimeter curve (as line segments) with the cutting lines. IMHO this fix does reduce the complexity of the inputs required for functionality. However, I'd still like @FraserGreenroyd to weigh in on the changes to the LINQ method changes as far as code legibility is concerned.

2021-03-23 16:15 UTC, FraserGreenroyd requested changes
I'm happy with the pre-processing that helps avoid taking lines outside the outer region and preventing the stack overflow occurring on overlapping lines, but I'm not happy with the changes to the LINQ bits. I know what they're doing, you know what they're doing, but someone else might not, and hiding the clause within the `Count` or `FirstOrDefault` methods obfuscates the filtering that is taking place. It places an onus on the next maintainer to know for definite what's going on. It also obfuscates the issue being reviewed as the code changes are greater than that suggested by the issue or PR itself. I can't see there being any great speed benefit after running the various test scripts we have for this for the change? If there is massive speed benefits that I'm not seeing then I could be persuaded, but at this moment, I feel we should focus only on the fix for the issue at hand, which is the stack overflow issue.

2021-03-23 16:27 UTC, pawelbaran commented
@FraserGreenroyd I do not agree with the obfuscation part of your comment - for me the code is more readable in the form proposed in this PR (on top of which, of course, you save a few ticks) - seems that this is a matter of preference. Following that, I will not be eager to change it back because:
- it is extra work, it would need a re-review
- as above, I prefer the syntax I proposed

It took me a solid afternoon to trace down this bug and effectively fix it (even though I was not involved in introducing it at all), therefore I would not mind avoiding any further effort as long as it is not really necessary. But feel free to commit the syntax changes you like if you convince @michaelhoehn to re-review 😉

2021-03-24 18:50 UTC, pawelbaran commented
@FraserGreenroyd, as promised I have added some more test content to @michaelhoehn's [test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232406%2DStackOverflowOnSplit%2DMH%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine). I would say it may become a UT one day, but I would rather wait for it until we get the engine methods merged together.

2021-03-24 19:57 UTC, michaelhoehn commented
Tested again with @FraserGreenroyd. This fix looks good to me. 🚀

2021-03-24 19:58 UTC, michaelhoehn approved these changes
Tested again with @FraserGreenroyd. Changes look good to me. 🚀

2021-03-24 20:05 UTC, pawelbaran commented
@BHoMBot check core

2021-03-24 20:05 UTC, pawelbaran commented
@BHoMBot check installer

2021-03-24 20:06 UTC, pawelbaran commented
@BHoMBot check serialisation

2021-03-24 20:06 UTC, pawelbaran commented
@BHoMBot check versioning

2021-03-24 20:06 UTC, pawelbaran commented
@BHoMBot check compliance

2021-03-24 20:08 UTC, FraserGreenroyd approved these changes
Tested through with the test scripts @pawelbaran and @michaelhoehn prepared along with the one I had from the original issue. Am happy this appears to be working and does resolve the stack overflow issue. As discussed on the call between @pawelbaran , myself, and @al-fisher , key to capture the full story of how we go for code changes to aid the review process and keep scope limited as much as possible to aid the review process :smile:

Hopefully the checks will come back green and we can merge @pawelbaran !

2021-03-24 20:42 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2021-03-24 20:48 UTC, merged

2021-03-24 21:40 UTC, al-fisher commented
Thanks @pawelbaran @FraserGreenroyd