Spatial_Engine: Remove Normal from RoundCoordinates
BHoM/BHoM_Engine pull request #2445
Opened 2021-04-07 14:56 UTC by LMarkowski

### Issues addressed by this PR

Closes #2441

Removed `Normal()` query from `IElement` and `PlanarSurface` `RoundCoordinates()` methods in the engine.
Also aligned `PlanarSurface` method to the recent changes in the `Spatial_Engine` methods. Rounding coordinates of sloped surfaces is now allowed if it won't mess the planarity.
It needed moving `FitPlane(IElement)` methods to the `Spatial_Engine`.

### Test files

[Here](https://burohappold.sharepoint.com/:f:/s/BHoM/EnBoJbstUktLil5ctcKL1RMBzSu3bcJPbdlfL87qQ5YwCA?e=YWDT2k) is the test for newly added FitPlane method.
[Here](https://burohappold.sharepoint.com/:f:/s/BHoM/Es7u_pVlelBHnMn4FMLckToBg_rAo9B9mua_D35VuZAdYw?e=DZBg8N) is the test file for Spatial RoundCoordinates methods.
And [here](https://burohappold.sharepoint.com/:f:/s/BHoM/En2Ibg00v25HmGzTJBBz76cBJaFHnTPrNFJoBsnZQo7SVQ?e=l2Nzjj) is the test file for Geometrical RoundCoordinates methods. It doesn't provide with a clean validation, but maybe in this case passing the UTs would be enough.

### Changelog

- Moved `FitPlane` methods for `IElement` classes to the `Spatial_Engine`.
- Added unit test for the  `FitPlane` methods in the `Spatial_Engine`.
- Updated `RoundCoordinates` method for the `IElement2D` class in the `Spatial_Engine`.
- Updated `RoundCoordinates` method for the `PlanarSurface` class in the `Geometry_Engine`.

2021-04-07 15:07 UTC, LMarkowski commented
@BHoMBot check unit-tests

2021-04-07 17:18 UTC, pawelbaran requested changes
From what I can see in the tests, the results of Geometry_Engine tests for `PlanarSurface` stay unchanged, but what is alarming, the `Spatial_Engine` test results for `IElement2D` goeds from 49 correct to 48. Is that possible or did I do something wrong?

Besides that, one minor code comment.

2021-04-07 17:18 UTC, pawelbaran commented on Geometry_Engine/Modify/RoundCoordinates.cs
> +            Vector normal = planarSurface.FitPlane().Normal;
`normal` could be declared inside the `if` statement.

2021-04-07 17:19 UTC, pawelbaran commented
Ah yest, unit tests confirm my findings 😉

2021-04-08 07:59 UTC, LMarkowski commented
> @pawelbaran: test results for IElement2D goes from 49 correct to 48.

Shoot. I forgot the #2428 is not merged yet. It should be 50 out of 50. Testing against the UT which is being updated is kinda pointless. I guess we should wait until #2428 gets merged and update from master then, or rebase this branch to 2428's. What do you think?

2021-04-08 09:24 UTC, pawelbaran commented
Rebase to another branch sounds like something @FraserGreenroyd will not be too happy about. I would start from updating from `master`, then rebase if necessary.

2021-04-09 15:28 UTC, pawelbaran commented
@LMarkowski I have just updated from `master`, but the test still shows 48/50 :<

2021-04-12 10:36 UTC, LMarkowski commented
@BHoMBot check unit-tests

2021-04-12 11:28 UTC, rolyhudson commented
I had a quick look at the grasshopper validation for `RoundCoordinates(IElement2D)` (which I think is the one referred to above) currently showing 48/50 pass. 

The validation compares the resulting coordinates of `RoundCoordinates(IElement2D)` with coordinates obtained by extracting controlpoints of the `ElementCurves`.

The validation fails for 2 `IElement2D`s whose coordinates are not rounded by `RoundCoordinates` 
They show the warning: 
`1. Rounding the coordinates of an IElement2D couldn't be achieved without losing planarity. No action has been taken.`

In the validation the un-rounded coordinates are still compared to rounded coordinates and therefore fail.

I think the issue is on the validation method not accounting for those IElement2D that cannot have coordinates rounded.
This looks like one where input of a tolerance parameter would be helpful. (As another issue under the tolerance theme https://github.com/BHoM/BHoM_Engine/issues/1773)

Meanwhile looking separately at the unit tests I observe them to all pass when running from within the UI but FitPlane and RoundCoordinates fail when tested without UI.

2021-04-14 11:49 UTC, LMarkowski commented
@BHoMBot check unit-tests

2021-04-14 13:53 UTC, LMarkowski commented
@BHoMBot check unit-tests

2021-04-14 13:59 UTC, LMarkowski commented
> The validation fails for 2 `IElement2D`s whose coordinates are not rounded by `RoundCoordinates`
> They show the warning:
> `1. Rounding the coordinates of an IElement2D couldn't be achieved without losing planarity. No action has been taken.`

Good point @rolyhudson! I actually made the validation tests to pick up those cases and mark them as true. And they did a good work. The problem was a bug that I made in previous commit which stopped the code from rounding the coordinates even when it was possible. 
Now both UTs and validation scripts should be happy.

@pawelbaran, I had to improve a bit the logic behind the method. I added a few comments to make clear what's going on. Could you check if they are clear (and maybe not necessary)?

2021-04-14 14:34 UTC, LMarkowski commented
![image](https://user-images.githubusercontent.com/48125514/114726053-5041fd80-9d3d-11eb-87e8-121758d1a2e0.png)
And here is how the failing `FitPlane` case looks in the grasshopper. Seems to again be an issue of numerical tolerance differences between our machines and VM. Not sure how to handle it. I don't feel good about pushing it on the master. I can remove failing case or move the whole file to the [quarantined unit tests](https://github.com/BuroHappoldEngineering/ModelLaundry_Toolkit/issues/310#issuecomment-766794783).

@rolyhudson  @FraserGreenroyd fyi

2021-04-15 07:45 UTC, rolyhudson commented
@LMarkowski I would say quarantine the unit test. 
Also it would be good to have a central store (or record) of these that includes (or references) the creation script and the resulting json dataset. 

When time permits we can dig deeper into the problem.

2021-04-15 08:43 UTC, LMarkowski commented
@BHoMBot check unit-tests

2021-04-15 10:38 UTC, rolyhudson submitted a review, later dismissed
LGTM

2021-04-15 21:01 UTC, pawelbaran requested changes
You asked for a second review @LMarkowski, so here it comes 😃 See the code comments.

I also have one thought, whether the code for `PlanarSurface` and `IElement2D` could not be unified by some means. My intuition says this does not make much sense, but did you consider that, any thoughts?

2021-04-16 09:08 UTC, LMarkowski commented on Spatial_Engine/Compute/FitPlane.cs
> +        [Output("plane", "Plane that fits best into the element's geometry. null if no singular solution exists.")]
I think it says so 🤔
`Always returns null for IElement0Ds.` at the end of line 41.

2021-04-16 09:37 UTC, LMarkowski commented
@pawelbaran I think the code for `PlanarSurface` an `IElement` is as unified as it is possible.
`IElement`s don't ensure planarity which allows for simply overwriting properties, but needs additional check if formerly planar elements hasn't been de-planarized. On the other hands `PlanarSurface` has to be planar what cuts on checks, but enforce creating the returned element via `Create` method (to be sure that the result is valid).
Besides those points the code is identical.

2021-04-16 09:37 UTC, pawelbaran commented on Spatial_Engine/Compute/FitPlane.cs
> +        [Output("plane", "Plane that fits best into the element's geometry. null if no singular solution exists.")]
Yeah but looks a bit inconsistent to me, line 41 vs 44. The message in 44 can be read that it is possible to create a plane, if there a singular solution for point. Or am I overreacting? 🐵

2021-04-16 09:47 UTC, pawelbaran commented
@BHoMBot check unit-tests

2021-04-16 10:05 UTC, pawelbaran commented
@BHoMBot check compliance

2021-04-16 10:14 UTC, pawelbaran commented
@BHoMBot check compliance

2021-04-16 10:14 UTC, pawelbaran commented
@BHoMBot check versioning

2021-04-16 10:14 UTC, pawelbaran commented
@BHoMBot check installer

2021-04-16 10:14 UTC, pawelbaran commented
@BHoMBot check core

2021-04-16 10:14 UTC, pawelbaran commented
@BHoMBot check serialisation

2021-04-16 10:42 UTC, LMarkowski commented
@BHoMBot check null-handling

2021-04-16 11:07 UTC, pawelbaran commented
@BHoMBot check compliance

2021-04-16 11:08 UTC, pawelbaran commented
@BHoMBot check core

2021-04-16 11:08 UTC, pawelbaran commented
@BHoMBot check installer

2021-04-16 11:08 UTC, pawelbaran commented
@BHoMBot check serialisation

2021-04-16 11:08 UTC, pawelbaran commented
@BHoMBot check versioning

2021-04-16 11:52 UTC, pawelbaran commented
@BHoMBot check serialisation

2021-04-16 11:54 UTC, pawelbaran commented
@BHoMBot check null-handling

2021-04-16 12:07 UTC, pawelbaran commented
@BHoMBot check versioning

2021-04-16 12:24 UTC, pawelbaran commented
@FraserGreenroyd would you be OK with getting the PR merged regardless of the compliance issues?

2021-04-16 12:56 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2361968817

2021-04-16 12:56 UTC, FraserGreenroyd commented
> @FraserGreenroyd would you be OK with getting the PR merged regardless of the compliance issues?

If someone wants to approve it then yes, I'm happy.

2021-04-16 13:42 UTC, pawelbaran approved these changes
.
..
...
....
.....

LGTM! 😃

2021-04-16 14:25 UTC, merged