Data_Engine: Handle nulls
BHoM/BHoM_Engine pull request #2467
Opened 2021-04-16 13:24 UTC by FraserGreenroyd

### Issues addressed by this PR
Fixes #2466 

### Test files

### Changelog

### Additional comments

2021-04-16 13:26 UTC, FraserGreenroyd commented
@BHoMBot check null-handling

2021-04-16 13:29 UTC, FraserGreenroyd commented
@BHoMBot check required

2021-04-16 13:57 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2362663582

2021-04-16 13:58 UTC, FraserGreenroyd commented
@BHoMbot check copyright-compliance

2021-04-16 13:58 UTC, FraserGreenroyd commented
@BHoMbot check dataset-compliance

2021-04-22 12:04 UTC, pawelbaran requested changes
In general similar thoughts as in #2465, on top of that I am concerned about returning a `CustomObject` instead of `null` - please see the code comments.

2021-04-22 12:04 UTC, pawelbaran commented on Data_Engine/Query/FirstValueAbove.cs
> +                return new CustomObject();
Why so?
```suggestion
                return null;
```

2021-04-22 12:04 UTC, pawelbaran commented on Data_Engine/Query/FirstValueAt.cs
> +                return new CustomObject();
Why so?
```suggestion
                return null;
```

2021-04-22 13:16 UTC, FraserGreenroyd commented
@BHoMBot check required

2021-04-22 13:45 UTC, pawelbaran approved these changes
I have no objections outside of what I have mentioned in my previous comments in previous PRs of this type.

As mentioned in #2465, I am a bit concerned about the creep that these changes may possibly introduce, but it seems that the only way to check it is to merge and see how many weird behaviours bubble up.

2021-04-22 13:58 UTC, FraserGreenroyd commented
@BHoMBot check dataset-compliance

2021-04-22 13:59 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2021-04-22 16:12 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2410470207

2021-04-22 16:12 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2410471166

2021-04-22 16:12 UTC, merged