Analytical_Engine: Handle nulls
BHoM/BHoM_Engine pull request #2473
Opened 2021-04-16 15:19 UTC by FraserGreenroyd

### Issues addressed by this PR
Fixes #2472 

### Test files

### Changelog

### Additional comments

2021-04-16 15:20 UTC, FraserGreenroyd commented
@BHoMBot check null-handling

2021-04-16 15:32 UTC, FraserGreenroyd commented
@BHoMBot check null-handling

2021-04-16 15:40 UTC, FraserGreenroyd commented
@BHoMBot check required

2021-04-22 12:00 UTC, pawelbaran approved these changes
Similarly to #2465, I have just pushed a commit changing the return object from null reference to `null`. Besides that I have no further objections outside of what I have mentioned in my previous comments in previous PRs of this type.

As mentioned in #2465, I am a bit concerned about the creep that these changes may possibly introduce, but it seems that the only way to check it is to merge and see how many weird behaviours bubble up.

2021-04-22 12:00 UTC, pawelbaran commented
@BHoMBot check null-handling

2021-04-22 12:31 UTC, pawelbaran requested changes
Changed my mind sorry - please see the code comments.

2021-04-22 12:31 UTC, pawelbaran commented on Analytical_Engine/Query/Graph/EntityNeighbourhood.cs
> +                return null;
Why not return a list to follow the pattern?
```suggestion
                return new List<Graph>();
```

2021-04-22 12:31 UTC, pawelbaran commented on Analytical_Engine/Query/Graph/FilterEntities.cs
> +                return null;
Why not return an empty collection to follow the pattern?
```suggestion
                return new Dictionary<Guid, IBHoMObject>();
```

2021-04-22 12:31 UTC, pawelbaran commented on Analytical_Engine/Query/Graph/FilterRelations.cs
> +                return null;
Why not return an empty collection to follow the pattern?
```suggestion
                return new List<IRelation>();
```

2021-04-22 12:31 UTC, pawelbaran commented on Analytical_Engine/Query/Graph/IsolatedEntities.cs
> +                return null;
Why not return an empty collection to follow the pattern?
```suggestion
                return new List<Guid>();
```

2021-04-22 12:31 UTC, pawelbaran commented on Analytical_Engine/Query/Graph/Relation.cs
> +                return null;
Why not return an empty collection to follow the pattern?
```suggestion
                return new List<IRelation>();
```

2021-04-22 12:31 UTC, pawelbaran commented on Analytical_Engine/Query/Graph/Relation.cs
> +                return null;
Why not return an empty collection to follow the pattern?
```suggestion
                return new List<IRelation>();
```

2021-04-22 12:31 UTC, pawelbaran commented on Analytical_Engine/Query/Graph/Relation.cs
> +                return null;
Why not return an empty collection to follow the pattern?
```suggestion
                return new List<IRelation>();
```

2021-04-22 12:31 UTC, pawelbaran commented on Analytical_Engine/Query/Graph/Relation.cs
> +                return null;
Why not return an empty collection to follow the pattern?
```suggestion
                return new List<Guid>();
```

2021-04-22 12:31 UTC, pawelbaran commented on Analytical_Engine/Query/Graph/Adjacency.cs
> +                return null;
Why not return an empty collection to follow the pattern?
```suggestion
                return new Dictionary<Guid, List<Guid>>();
```

2021-04-22 13:18 UTC, FraserGreenroyd commented
@BHoMBot check required

2021-04-22 13:47 UTC, pawelbaran requested changes

2021-04-22 13:47 UTC, pawelbaran commented on Analytical_Engine/Query/Graph/Depth.cs
> +                return null;
To follow a single pattern:
```suggestion
                return new Dictionary<Guid, int>();
```

2021-04-22 14:34 UTC, pawelbaran approved these changes
I have no objections outside of what I have mentioned in my previous comments in previous PRs of this type.

As mentioned in #2465, I am a bit concerned about the creep that these changes may possibly introduce, but it seems that the only way to check it is to merge and see how many weird behaviours bubble up.

2021-04-22 14:34 UTC, pawelbaran commented
@BHoMBot check required

2021-04-22 15:58 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2021-04-22 15:58 UTC, FraserGreenroyd commented
@BHoMBot check dataset-compliance

2021-04-22 16:10 UTC, FraserGreenroyd commented
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2411206415

2021-04-22 16:11 UTC, merged