Structure_Engine: Replace calls to GetShallowClone
BHoM/BHoM_Engine pull request #2550
Opened 2021-07-26 10:52 UTC by alelom

### Issues addressed by this PR

Closes #2201

See BHoM/admin#9

### Test files

Just compliance, should mean no functional change

### Changelog

### Additional comments

2021-07-26 11:31 UTC, peterjamesnugent submitted a review, later dismissed
LGTM.

2021-07-26 12:11 UTC, alelom commented
Thanks @peterjamesnugent , I realized I missed to replace a call to IClone.

2021-07-26 12:22 UTC, peterjamesnugent submitted a review, later dismissed
LGTM - did a quick search and there's no more uses of `IClone` or `GetShallowClone` in Structure_Engine.

2021-07-27 15:14 UTC, alelom commented
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

2021-07-28 14:56 UTC, FraserGreenroyd requested changes

2021-07-28 14:56 UTC, FraserGreenroyd commented on Structure_Engine/Modify/Transform.cs
> +            Node result = node.ShallowClone() as Node;
```suggestion
            Node result = node.ShallowClone();
```

2021-07-28 14:56 UTC, FraserGreenroyd commented on Structure_Engine/Modify/Transform.cs
> +            Bar result = bar.ShallowClone() as Bar;
```suggestion
            Bar result = bar.ShallowClone();
```

2021-07-28 14:56 UTC, FraserGreenroyd commented on Structure_Engine/Modify/Transform.cs
> +            RigidLink result = link.ShallowClone() as RigidLink;
```suggestion
            RigidLink result = link.ShallowClone();
```

2021-07-28 14:56 UTC, FraserGreenroyd commented on Structure_Engine/Modify/Transform.cs
> +            Edge result = edge.ShallowClone() as Edge;
```suggestion
            Edge result = edge.ShallowClone();
```

2021-07-28 14:56 UTC, FraserGreenroyd commented on Structure_Engine/Modify/Transform.cs
> +            Opening result = opening.ShallowClone() as Opening;
```suggestion
            Opening result = opening.ShallowClone();
```

2021-07-28 14:56 UTC, FraserGreenroyd commented on Structure_Engine/Modify/Transform.cs
> +            Panel result = panel.ShallowClone() as Panel;
```suggestion
            Panel result = panel.ShallowClone();
```

2021-07-28 14:56 UTC, FraserGreenroyd commented on Structure_Engine/Modify/Transform.cs
> +            FEMesh result = mesh.ShallowClone() as FEMesh;
```suggestion
            FEMesh result = mesh.ShallowClone();
```

2021-07-28 14:57 UTC, FraserGreenroyd requested changes
This PR has the same files changed as #2552 
I am prioritising #2552 for merge because it has already started the checks.

@alelom can you confirm the state of Facades_Engine as a result?

2021-07-28 15:02 UTC, FraserGreenroyd commented
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

2021-07-28 20:55 UTC, peterjamesnugent approved these changes
LGTM.

2021-07-29 07:44 UTC, merged