MEP_Engine: replace calls to GetShallowClone
BHoM/BHoM_Engine pull request #2558
Opened 2021-07-26 11:14 UTC by alelom

### Issues addressed by this PR

Closes #2557

### Test files

Just compliance, should mean no functional change

### Changelog

### Additional comments

2021-07-26 14:15 UTC, FraserGreenroyd approved these changes
LGTM

2021-07-28 14:51 UTC, FraserGreenroyd requested changes
This PR relates entirely to Physical_Engine, which has already been reviewed and merged in #2556 

@alelom can you check the files changed for this branch? I think there might have been an issue with changing branches to fix whatever was needed for MEP Engine?

2021-07-28 15:06 UTC, alelom commented
> This PR relates entirely to Physical_Engine

my bad. Must've confused where I launched my Find-Replace 😄 

Should be ok now. @FraserGreenroyd

2021-07-28 15:08 UTC, FraserGreenroyd requested changes

2021-07-28 15:08 UTC, FraserGreenroyd commented on MEP_Engine/Modify/Transform.cs
> +            CableTray result = cableTray.ShallowClone() as CableTray;
```suggestion
            CableTray result = cableTray.ShallowClone();
```

2021-07-28 15:08 UTC, FraserGreenroyd commented on MEP_Engine/Modify/Transform.cs
> +            Duct result = duct.ShallowClone() as Duct;
```suggestion
            Duct result = duct.ShallowClone();
```

2021-07-28 15:09 UTC, FraserGreenroyd approved these changes

2021-07-28 15:10 UTC, FraserGreenroyd commented
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

2021-07-29 08:11 UTC, FraserGreenroyd commented
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

2021-07-29 08:11 UTC, FraserGreenroyd approved these changes

2021-07-29 09:22 UTC, merged