Lighting_Engine: Remove calls to GetShallowClone
BHoM/BHoM_Engine pull request #2563
Opened 2021-07-26 11:42 UTC by alelom

### Issues addressed by this PR

Closes #2560 

### Test files

### Changelog

### Additional comments

2021-07-27 05:26 UTC, adecler submitted a review, later dismissed

2021-07-28 14:51 UTC, FraserGreenroyd requested changes

2021-07-28 14:51 UTC, FraserGreenroyd commented on Lighting_Engine/Modify/Transform.cs
> +            Luminaire result = luminaire.ShallowClone() as Luminaire;
```suggestion
            Luminaire result = luminaire.ShallowClone();
```

2021-07-28 14:52 UTC, FraserGreenroyd commented
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

2021-07-28 14:54 UTC, FraserGreenroyd approved these changes

2021-07-28 15:10 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2021-07-29 07:44 UTC, merged