Environment_Engine: Create openings from a panel
BHoM/BHoM_Engine pull request #2635
Opened 2021-09-30 13:52 UTC by robinflyman

Closes #2595 

Created a method to create openings from a panel.

2021-12-02 16:31 UTC, robinflyman commented
@BHoMBot check required

2022-01-13 17:27 UTC, FraserGreenroyd requested changes

2022-01-13 17:27 UTC, FraserGreenroyd commented on Environment_Engine/Convert/OpeningFromPanel.cs
> +using BH.oM.Reflection.Attributes;
```suggestion
using BH.oM.Base.Attributes;
```

2022-01-13 17:27 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-01-17 11:22 UTC, FraserGreenroyd requested changes

2022-01-17 11:22 UTC, FraserGreenroyd commented on Environment_Engine/Convert/OpeningFromPanel.cs
> +using BH.oM.Reflection.Attributes;
```suggestion
using BH.oM.Base.Attributes;
```

2022-01-17 11:22 UTC, FraserGreenroyd commented
@BHoMBot check core

2022-01-17 11:23 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-01-17 11:53 UTC, FraserGreenroyd approved these changes

2022-01-17 11:53 UTC, FraserGreenroyd requested changes

2022-01-17 11:53 UTC, FraserGreenroyd commented on Environment_Engine/Convert/OpeningFromPanel.cs
> + * Copyright (c) 2015 - 2021, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
```

2022-01-17 11:55 UTC, FraserGreenroyd commented
Final commit was only to copyright, all checks had passed that were required on the previous commit. Am therefore granting neutral checks to avoid over using bot resource.

2022-01-17 11:55 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting a neutral check on: core, versioning, installer, project-compliance, ready-to-merge, documentation-compliance, code-compliance, null-handling, dataset-compliance

2022-01-17 11:59 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2022-01-17 11:59 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: serialisation

2022-01-17 12:00 UTC, merged