Physical_Engine: Methods to query dimensions from Openings added
BHoM/BHoM_Engine pull request #2683
Opened 2021-11-10 14:40 UTC by tiagogrossi

### Issues addressed by this PR

Closes #2675 

Following the example from `Environment`, a couple of dimension query methods have been added for openings, with specific implementation of Doors. Other opening objects will have to be implemented when required.

### Test files
Create a BHoM Door object and query its dimensions, like in this sample [file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Physical_Engine/Physical_Engine-%232675-AddQueryOpeningDimensions.gh?csf=1&web=1&e=a75Jpt) 

### Changelog
Added `BH.Engine.Geometry.Query.Width`
Added `BH.Engine.Geometry.Query.Height`
Added `BH.Engine.Physical.Query.Height`
Added `BH.Engine.Physical.Query.Width`
Added `BH.Engine.Physical.Query.Bottom`

### Additional comments
@FraserGreenroyd these methods are a repurposing of existing public and private methods in `Environment`. Since other toolkit might take advantage of it I copied some of it to `Geometry_Engine`, and if this is deemed appropriate I reckon `Environment` could adjust its relevant code to use it instead.

2021-11-10 15:13 UTC, IsakNaslundBh requested changes
Have put some initial reviews below.

Also, think the descriptions needs to be exapanded to tell more what they are doing. FOr example, this is giving heights in widths in global coordinates. An opening that was tilted for whatever reason would not give the dimension of it in its own plane, but just the global coordinate boundingbox distance (same before my suggested changes and after).

With that said, can see the use of the methods, but again, need to be described to clearly state what they are doing.

2021-11-10 15:13 UTC, IsakNaslundBh commented on Physical_Engine/Query/Height.cs
> +        }
Think this gets cleaner if it is dealt with straight in the physical_Engine, without a roundtrip by extracting the geometry. Think something like the suggested below should solve it.

Have also added the Length quantity attribute that should be put on any output returning a length of something :).

```suggestion
using BH.oM.Geometry;
using BH.Engine.Geometry;
using BH.Engine.Spatial;
using BH.oM.Quantities.Attributes;

namespace BH.Engine.Physical
{
    public static partial class Query
    {
        /***************************************************/
        /****               Public Methods              ****/
        /***************************************************/

        [Description("Returns the height of a generic opening.")]
        [Input("opening", "A generic Opening object.")]
        [Output("height", "The total height of the generic opening.", typeof(Length))]
        public static double Height(this IOpening opening)
        {
            if (opening == null)
            {
                BH.Engine.Reflection.Compute.RecordError("Cannot query the height of a null opening.");
                return 0;
            }
            BoundingBox bBox = opening.IBounds();
            return (bBox.Max.Z - bBox.Min.Z);
        }
```

2021-11-10 15:13 UTC, IsakNaslundBh commented on Physical_Engine/Query/Width.cs
> +        }
Same as for the height method. Think this is better dealt with in the physical engine.

```suggestion
using BH.oM.Geometry;
using BH.Engine.Spatial;
using BH.oM.Quantities.Attributes;

namespace BH.Engine.Physical
{
    public static partial class Query
    {
        /***************************************************/
        /****               Public Methods              ****/
        /***************************************************/

        [Description("Returns the width of a generic opening.")]
        [Input("opening", "A generic Opening object.")]
        [Output("width", "The total width of the generic opening.", typeof(Length))]
        public static double Width(this IOpening opening)
        {
            if (opening == null)
            {
                BH.Engine.Reflection.Compute.RecordError("Cannot query the width of a null opening.");
                return 0;
            }

            BoundingBox bBox = opening.IBounds();

            double diffX = Math.Abs(bBox.Max.X - bBox.Min.X);
            double diffY = Math.Abs(bBox.Max.Y - bBox.Min.Y);

            return Math.Sqrt((diffX * diffX) + (diffY * diffY));
        }
```

2021-11-10 16:37 UTC, tiagogrossi commented
@IsakNaslundBh thanks for the review! I agree with you that it seemed a bit awkward going to `Geometry` and then to `Physical`, I've done that because this whole thing exists already in `Environment`, but some methods are private, and therefore I thought we could just move it `Geometry` and any other toolkit could use it. Would you still be in favor of each toolkit that needs to handle it privately?

2021-11-11 09:18 UTC, IsakNaslundBh commented
> @IsakNaslundBh thanks for the review! I agree with you that it seemed a bit awkward going to `Geometry` and then to `Physical`, I've done that because this whole thing exists already in `Environment`, but some methods are private, and therefore I thought we could just move it `Geometry` and any other toolkit could use it. Would you still be in favor of each toolkit that needs to handle it privately?

Think my take on this is twofold, and why I suggested the changes I made:

1. To me it does not make sense to have a method in Geometry_Engine that measures the the `Width` or `Height` of a curve. My basic argument to that is that those are not well defined measurements for _any_ curve. To exemplify, what is the width of a line? (there are ofc exceptions, like if we added had a `Rectangle` class or similar, but then the current implementation would not work anyway). 
2. You do not need to measure the curve. as the curve method was working on the basis of the `BoundingBox` of the outline curve anyway. As we already have methods for getting out `BoundingBox` for any `IElement2d` (at least for planar versions) it feels more sensible to just get that out straight away and do the processing on it.

I could potentially see us adding a `Height` method for the `BoundingBox` class in geometry engine, as well as `HorizontalDiagonalLength` (or similar) for the current implementation of the `Width`, as those are querible properties that would be well defined for the class, in all cases.

2021-11-11 11:38 UTC, tiagogrossi commented
Good point @IsakNaslundBh , boundingbox does makes more sense. I've made the necessary changes and added more detail to the descriptions.

2021-11-11 11:40 UTC, tiagogrossi commented
@BHoMBot check compliance

2021-11-11 14:16 UTC, IsakNaslundBh requested changes
Some more comments below. Mainly name of the method currently called "Width" for the bounding box, and for correct quantity attributes to be assigned to all of the outputs.

2021-11-11 14:16 UTC, IsakNaslundBh commented on Geometry_Engine/Query/Height.cs
> +        [Output("height", "The height of the BoundingBox based on the difference in Z minimum and maximum values.")]
The output here should have the Length quantity attribute added. Make sure you add the Using of `BH.oM.Quantities.Attributes` as well.

This should be updated for all methods.

```suggestion
        [Output("height", "The height of the BoundingBox based on the difference in Z minimum and maximum values.", typeof(Length))]
```

2021-11-11 14:16 UTC, IsakNaslundBh commented on Geometry_Engine/Query/Width.cs
> +        public static double Width(this BoundingBox boundingBox)
Don't think Width is the right name for this method. Would call it something like `HorizontalDiagonalLength` or similar. Does not need to be exactly that, but needs to be something that states what the method is returning.

2021-11-11 14:16 UTC, IsakNaslundBh commented on Physical_Engine/Query/Height.cs
> +            return Height(opening as dynamic);
This needs a null check.

2021-11-11 14:16 UTC, IsakNaslundBh commented on Physical_Engine/Query/Height.cs
> +            return BH.Engine.Geometry.Query.Height(door.Location.IBounds());
By adding the using of Spatial_Engine, you could query the bounds straight from the door. That is just details though, and I actually think what you have here might be quicker anyway.

2021-11-11 14:16 UTC, IsakNaslundBh commented on Physical_Engine/Query/Width.cs
> +            return Width(opening as dynamic);
again, null check needed

2021-11-12 10:55 UTC, IsakNaslundBh approved these changes
Now lgtm

2021-11-12 12:00 UTC, tiagogrossi commented
@BHoMBot check required

2021-11-12 12:25 UTC, tiagogrossi commented
@BHoMBot check compliance

2021-11-12 13:13 UTC, tiagogrossi commented
@BHoMBot check required

2021-11-12 14:24 UTC, tiagogrossi commented
@BHoMBot check serialisation

2021-11-15 09:22 UTC, tiagogrossi commented
@BHoMBot check serialisation

2021-11-15 09:38 UTC, IsakNaslundBh approved these changes
Re-approving after compliance updates

2021-11-15 09:38 UTC, IsakNaslundBh commented
@BHoMBot check ready-to-merge

2021-11-15 09:42 UTC, merged