Created new methods for IsShade
BHoM/BHoM_Engine pull request #2793
Opened 2022-04-20 11:28 UTC by robinflyman

Closes #2792 

Added IsShade methods according to Frasers suggestion.

2022-04-20 15:28 UTC, robinflyman commented
@BHoMBot check versioning

2022-04-20 18:29 UTC, FraserGreenroyd requested changes
In addition to the versioning - see my code suggestions.

You need to delete `Geometry_Engine/Geometry_Engine - Backup.csproj` and `Graphics_Engine/Graphics_Engine - Backup.csproj` and commit the deletions as neither of those files are required.

2022-04-20 18:29 UTC, FraserGreenroyd commented on Environment_Engine/Modify/SetShadePanels.cs
> +        [Input("panelType", "A panelType enum.")]
```suggestion
        [Input("shadeType", "The type of shade to assign to the shade panels.")]
```

2022-04-20 18:29 UTC, FraserGreenroyd commented on Environment_Engine/Modify/SetShadePanels.cs
> +        public static List<Panel> SetShadePanels(this List<Panel> panels, PanelType panelType = PanelType.Shade)
```suggestion
        public static List<Panel> SetShadePanels(this List<Panel> panels, PanelType shadeType = PanelType.Shade)
```

2022-04-20 18:29 UTC, FraserGreenroyd commented on Environment_Engine/Modify/SetShadePanels.cs
> +            if (!panelType.IsShade())
```suggestion
            if (!shadeType.IsShade())
```

2022-04-20 18:29 UTC, FraserGreenroyd commented on Environment_Engine/Modify/SetShadePanels.cs
> +                    panel.Type = panelType;
```suggestion
                    panel.Type = shadeType;
```

2022-04-20 18:29 UTC, FraserGreenroyd commented on Environment_Engine/Query/IsShade.cs
> +        [Output("Boolean", "Will return true if the paneltype is a shade-type.")]
```suggestion
        [Output("isShade", "Will return true if the provided panel type is a shade-type.")]
```

2022-04-20 18:29 UTC, FraserGreenroyd commented on Environment_Engine/Query/IsShade.cs
> +
```suggestion
```

2022-04-20 18:29 UTC, FraserGreenroyd commented on Environment_Engine/Query/IsShade.cs
> +        [Description("Method will check what type the Paneltype is, and return false if it's not a shade-type.")]
```suggestion
        [Description("Ascertain whether a given panel is a shading panel.")]
```

2022-04-20 18:29 UTC, FraserGreenroyd commented on Environment_Engine/Query/IsShade.cs
> +        [Input("Panel", "Panel to determine if it's a shade-type or not.")]
```suggestion
        [Input("panel", "Panel to determine if it's a shade-type or not.")]
```

2022-04-20 18:29 UTC, FraserGreenroyd commented on Environment_Engine/Query/IsShade.cs
> +        [Output("Boolean", "Will return true if the paneltype is a shade-type.")]
```suggestion
        [Output("isShade", "Will return true if the panel is a shade-type.")]
```

2022-04-20 18:29 UTC, FraserGreenroyd commented on Environment_Engine/Query/IsShade.cs
> +
```suggestion
```

2022-04-21 13:56 UTC, robinflyman commented
@BHoMBot check versioning

2022-04-25 20:45 UTC, FraserGreenroyd requested changes

2022-04-25 20:45 UTC, FraserGreenroyd commented on Environment_Engine/Modify/SetShadePanels.cs
> +        public static List<Panel> SetShadePanels(this List<Panel> panels, PanelType shadeType = PanelType.Shade)
```suggestion
        [Output("shadePanels", "BHoM Environment panel representing the shade.")]
        [PreviousVersion("5.2", "BH.Engine.Environment.Modify.SetShadePanels(System.Collections.Generic.List<BH.oM.Environment.Elements.Panel>)")]
        public static List<Panel> SetShadePanels(this List<Panel> panels, PanelType shadeType = PanelType.Shade)
```

2022-04-25 20:47 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2022-04-26 08:15 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2022-04-26 08:17 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-04-26 12:47 UTC, jamesramsden-bh requested changes
Couple of spelling errors noticed. Haven't yet tested functionality.

2022-04-26 12:47 UTC, jamesramsden-bh commented on Environment_Engine/Query/IsShade.cs
> +        [Description("Acertain whether a given panel is a shading panel.")]
Ascertain

2022-04-26 12:47 UTC, jamesramsden-bh commented on Environment_Engine/Query/IsShade.cs
> +        [Description("Acertain whether a given panel type is an acceptable shade type.")]
Ascertain

2022-04-26 12:57 UTC, jamesramsden-bh commented on Environment_Engine/Query/IsShade.cs
> +        [Description("Acertain whether a given panel type is an acceptable shade type.")]
Actually, I probably would reword this. Something like "Ascertain whether a given PanelType is a type of shade."

2022-07-25 15:50 UTC, jamesramsden-bh approved these changes
Checked a panel with different panel types as below. isShade returns the correct value. 

![image](https://user-images.githubusercontent.com/84443868/180820887-e60d10d1-e3f8-4dae-af22-6507ed41becb.png)

2022-07-25 16:17 UTC, FraserGreenroyd commented
@BHoMBot check versioning
@BHoMBot check installer

2022-07-26 10:18 UTC, FraserGreenroyd commented
@BHoMBot check versioning
@BHoMBot check installer

2022-07-26 10:53 UTC, FraserGreenroyd requested changes

2022-07-26 10:53 UTC, FraserGreenroyd commented on Environment_Engine/Modify/SetShadePanels.cs
> +        public static List<Panel> SetShadePanels(this List<Panel> panels, PanelType shadeType = PanelType.Shade)
```suggestion
        [PreviousVersion("5.3", "BH.Engine.Environment.Modify.SetShadePanels(System.Collections.Generic.List<BH.oM.Environment.Elements.Panel>)")]
        public static List<Panel> SetShadePanels(this List<Panel> panels, PanelType shadeType = PanelType.Shade)
```

2022-07-26 10:54 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2022-07-26 15:53 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-07-26 16:00 UTC, FraserGreenroyd approved these changes

2022-07-26 16:07 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 7524112114

2022-07-26 16:09 UTC, merged