Data_Engine: Set Name and Tag in AsCustomObject()
BHoM/BHoM_Engine pull request #2821
Opened 2022-05-11 21:34 UTC by JosefTaylor

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #2820

### Test files

### Changelog

### Additional comments

2022-05-11 21:45 UTC, JosefTaylor commented
@BHoMBot check compliance

2022-05-12 06:44 UTC, IsakNaslundBh commented
@BHoMBot check required

2022-05-12 07:07 UTC, IsakNaslundBh requested changes
Good catch!

Think this just need a slight adjustment as code currently adds the name to both the Name proeprty and to the Name key in the dictionary (without the `else if` on the tags, the `else` only is in relation to the Tags).

With that change I think this is good to go!

2022-05-12 07:07 UTC, IsakNaslundBh commented on Data_Engine/Query/ValuesAt.cs
> +                if (col.ColumnName == "Tags")
```suggestion
                else if (col.ColumnName == "Tags")
```

2022-05-12 13:16 UTC, IsakNaslundBh submitted a review, later dismissed
Change makes sense to me. Tested and approved!

2022-05-12 13:58 UTC, JosefTaylor commented
@BHoMBot check compliance
@BHoMBot check required

2022-05-12 14:43 UTC, IsakNaslundBh approved these changes
Tested, works great. Approved

2022-05-12 14:57 UTC, merged