Reflection_Engine: Subtypes query added
BHoM/BHoM_Engine pull request #2965
Opened 2022-12-20 13:29 UTC by pawelbaran

### Issues addressed by this PR

Closes #2964

### Test files

On [SharePoint]()

### Changelog

### Additional comments

2022-12-20 18:03 UTC, FraserGreenroyd reviewed
I can see the primary differences between the methods is that one is specifically for interfaces and the other (the new one, `SubTypes`) is not.

Originally, I would say I wouldn't see the point of the second given the BHoM inheritance structure prohibits object inheritance, however we have broken that rule in strategic places, so I can see a reason for wanting to know the subtypes of non-interface types.

But I'm not sure we need two methods to achieve this. I think a `bool` flag on `ImplementingTypes` for `interfaceOnly` would suffice? While I like the attempt to keep it tidy by having one call the other, I'm just not convinced the use case for individual methods is that strong as opposed to a modification of the existing one?

Though maybe the default bool could cause confusion so I can also see an argument for having them as separate methods... Happy to see what others think for a final decision I think.

2022-12-21 22:06 UTC, pawelbaran commented
Hmm, I got confused now @FraserGreenroyd. The facts as I see them:
- both methods return only non-abstract, non-interface BHoM types
- `ImplementingTypes` method accepts only interface types, while `Subtypes` will be happy with any input of type `Type`
- technically `ImplementingTypes` is the same method as `Subtypes`, just more strict on the input properties

...`bool` input parameter seems a bit redundant to me in this case, I was more considering whether we need `ImplementingTypes` altogether. Or am I missing something?

2023-01-06 17:05 UTC, FraserGreenroyd requested changes
Happy with the discussion from above - could we generate a unit test for this before merge though @pawelbaran ?

2023-01-06 17:05 UTC, FraserGreenroyd commented on Reflection_Engine/Query/Subtypes.cs
> + * Copyright (c) 2015 - 2022, the respective contributors. All rights reserved.
```suggestion
 * Copyright (c) 2015 - 2023, the respective contributors. All rights reserved.
```

2023-01-06 17:31 UTC, pawelbaran commented
I will generate UTs on Monday @FraserGreenroyd - thanks!

2023-01-09 11:20 UTC, FraserGreenroyd requested changes

2023-01-09 11:20 UTC, FraserGreenroyd commented on Reflection_Engine/Query/Subtypes.cs
> +
```suggestion
```

2023-01-09 12:41 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-01-09 13:49 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

2023-01-09 13:50 UTC, FraserGreenroyd approved these changes
Code works and looks good, happy to deploy to support the Mongo work as this can be merged independently.

2023-01-09 13:51 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-01-09 13:58 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge

2023-01-09 13:58 UTC, merged