Reflection_Engine: add BaseTypes to collect all base types of a type
BHoM/BHoM_Engine pull request #2974
Opened 2023-01-03 14:12 UTC by alelom

### Issues addressed by this PR

Closes #2973

### Test files

See https://github.com/BHoM/BHoM_Adapter/pull/332

### Changelog

### Additional comments

2023-01-03 14:40 UTC, IsakNaslundBh requested changes
Some tweaks to where things go to align with other parts of the engine.

2023-01-03 14:40 UTC, IsakNaslundBh commented on Reflection_Engine/Query/BaseTypes.cs
> +        private static Dictionary<Type, List<Type>> m_cachedBaseTypes = new Dictionary<Type, List<Type>>();
please move to the bottom of the file, under a header of Private fields. as done [elsewhere](https://github.com/BHoM/BHoM_Engine/blob/develop/BHoM_Engine/Compute/RunExtensionMethod.cs)

Should also capitalise the c `m_CachedBaseTypes`

2023-01-03 14:40 UTC, IsakNaslundBh commented on Reflection_Engine/Query/BaseTypes.cs
> +    }
this might be fixed by above comment, but needs ending `/***************************************************/` after the last method

2023-01-03 15:22 UTC, IsakNaslundBh commented on Reflection_Engine/Query/BaseTypes.cs
> +            Type baseType = type.BaseType;
SHould probably keep on digging for more basetypes. More than one level of inheritance is currently breaking BHoM compliance, so should not really come up in practice for BHoM types, but might as well. Simple while loop keeping on checking base type of the base type should be enough.

2023-01-03 17:34 UTC, FraserGreenroyd commented
For this PR, make sure the unit test only uses types available to the repository if you only built this repository and its dependencies, in this case, BHoM. Don't fall into the trap I did when doing types based unit tests and thinking I could use any type I had on my machine 😄

2023-01-04 08:49 UTC, IsakNaslundBh commented
@BHoMBot  check compliance

2023-01-04 15:26 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-01-04 16:20 UTC, alelom commented
@BHoMBot check installer

2023-01-04 16:52 UTC, FraserGreenroyd commented
@BHoMBot check versioning
@BHoMBot check unit-tests
@BHoMBot check serialisation
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check ready-to-merge

2023-01-04 17:07 UTC, FraserGreenroyd approved these changes
Happy for this to go in, worked/seen working with @alelom and @IsakNaslundBh during PR closure call.

2023-01-04 17:07 UTC, merged