Base_Engine: add method to unpack `IContainer`s
BHoM/BHoM_Engine pull request #3001
Opened 2023-01-26 12:25 UTC by alelom

### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1467
   
### Issues addressed by this PR

Closes https://github.com/BHoM/BHoM_Engine/issues/3000

### Test files

### Changelog

### Additional comments

2023-02-17 14:06 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-20 12:43 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

2023-02-20 12:50 UTC, FraserGreenroyd requested changes

2023-02-20 12:50 UTC, FraserGreenroyd commented on .ci/code/Verification.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Engine_Test", "Engine_Test\Engine_Test.csproj", "{A02B86C5-9877-4618-88EA-0A308CA52F2B}"
I'm not sure this file should have received any changes?

2023-02-20 12:50 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

2023-02-20 12:55 UTC, FraserGreenroyd requested changes

2023-02-20 12:55 UTC, FraserGreenroyd commented on .ci/unit_tests/BHoM_Engine_Tests.sln
> +﻿
Folder should be `unit-tests` not `unit_tests`

2023-02-20 13:56 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

2023-02-20 14:33 UTC, IsakNaslundBh reviewed
Happy with the functionality of the added Engine method and happy with this to get merged as soon as @FraserGreenroyd is happy with the .ci folder additions.

2023-02-20 14:40 UTC, FraserGreenroyd requested changes

2023-02-20 14:40 UTC, FraserGreenroyd commented on .ci/unit_tests/Base_Engine_Tests/Base_Engine_Tests.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Missing postbuild to move this DLL to the assemblies folder.

`if not "$(ConfigurationName)" == "Test" (xcopy "$(TargetDir)$(TargetFileName)"  "C:\ProgramData\BHoM\Assemblies" /Y)`

2023-02-20 14:53 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-20 15:02 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-20 15:43 UTC, FraserGreenroyd commented on .ci/code/Verification.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Engine_Test", "Engine_Test\Engine_Test.csproj", "{A02B86C5-9877-4618-88EA-0A308CA52F2B}"
What?? No! The `.ci/code` folder (and associated `Verification.sln` file) is used for Serialisation and Null Handling checks by the bot - it cannot be emptied/deleted

2023-02-20 15:55 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-20 16:34 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-20 16:36 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-20 17:20 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-20 17:22 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-20 17:37 UTC, FraserGreenroyd requested changes

2023-02-20 17:37 UTC, FraserGreenroyd commented on .ci/unit-tests/Base_Engine_Tests/Base_Engine_Tests.csproj
> +    <Exec Command="if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)$(TargetFileName)&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y)&#xD;&#xA;if not &quot;$(
```suggestion
    <Exec Command="if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)$(TargetFileName)&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)Bogus.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)System.Data.DataSetExtensions.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)Microsoft.VisualStudio.CodeCoverage.Shim.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)Microsoft.TestPlatform.*.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)testhost.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)NuGet.Frameworks.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)System.Reflection.Metadata.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)Newtonsoft.Json.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)nunit.framework.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)DiffEngine.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)System.Management.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)EmptyFiles.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y" />
```

2023-02-21 12:07 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-21 12:24 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-21 15:58 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-21 16:06 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-21 16:16 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting force checks on: unit-tests

2023-02-21 17:28 UTC, FraserGreenroyd requested changes

2023-02-21 17:28 UTC, FraserGreenroyd commented on .ci/unit-tests/Base_Engine_Tests/Base_Engine_Tests.csproj
> +    <Exec Command="if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)$(TargetFileName)&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y)&#xD;&#xA;&#xD;&#xA;if no
```suggestion
    <Exec Command="if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)$(TargetFileName)&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)*Bogus.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)System.Data.DataSetExtensions.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)Microsoft.VisualStudio.*.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)Microsoft.TestPlatform.*.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)testhost.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)NuGet.Frameworks.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)System.Reflection.Metadata.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)Newtonsoft.Json.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)nunit.framework.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)DiffEngine.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)System.Management.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)EmptyFiles.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y&#xD;&#xA;if not &quot;$(ConfigurationName)&quot; == &quot;Test&quot; xcopy &quot;$(TargetDir)Shouldly.dll&quot;  &quot;$(ProgramData)\BHoM\Assemblies&quot; /Y" />
```

2023-02-22 12:11 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-22 12:16 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-22 12:29 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-22 12:31 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-22 12:35 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-22 12:38 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-22 16:14 UTC, alelom commented
"NUnit testing" tests have now been removed (https://github.com/BHoM/BHoM_Engine/pull/3001/commits/89ab6fa12c124d67cca9d26e2b4784fd2bcbe15e) and this PR is now ready for final review/approve/merge. 
@IsakNaslundBh @FraserGreenroyd

2023-02-22 16:15 UTC, alelom commented
@BHoMBot check unit-tests

2023-02-22 16:15 UTC, alelom commented
@BHoMBot check required

2023-02-22 16:51 UTC, FraserGreenroyd commented
@BHoMBot check core

2023-02-27 15:52 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-27 16:08 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-27 18:31 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-28 09:47 UTC, FraserGreenroyd commented
@BHoMBot check unit-tests

2023-02-28 10:02 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-02-28 11:28 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-02-28 14:19 UTC, FraserGreenroyd commented
@BHoMBot check installer

2023-02-28 14:39 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check null-handling

2023-02-28 15:29 UTC, FraserGreenroyd approved these changes
Approving based on @IsakNaslundBh review - only unit-tests updated.

2023-02-28 15:29 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-02-28 17:49 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge, code-compliance, documentation-compliance, project-compliance

2023-02-28 17:49 UTC, merged