Structure_Engine - Adding tolerance to create panel methods
BHoM/BHoM_Engine pull request #3005
Opened 2023-02-09 17:03 UTC by adecler

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #2961 

Adding tolerance the the Create.Panel methods in the Structural engine. At least for the ones where that makes sense. The other ones don't require any checks that involve the tolerance.

### Test files
[CreatePlanarCurveWithTolerance.zip](https://github.com/BHoM/BHoM_Engine/files/10699657/CreatePlanarCurveWithTolerance.zip)

### Changelog

### Additional comments

2023-02-09 17:12 UTC, michaelhoehn submitted a review, later dismissed
I've reviewed the code and tested the provided script successfully with the new additional tolerance input.

2023-02-10 12:28 UTC, FraserGreenroyd requested changes

2023-02-10 12:28 UTC, FraserGreenroyd commented on Structure_Engine/Create/Elements/Panel.cs
> +        [PreviousVersion("6.0", "BH.Engine.Structure.Create.Panel(BH.oM.Geometry.ICurve, System.Collections.Generic.List<BH.oM.Geometry.ICurve>, BH.oM.Structure.SurfaceProperties.ISurfaceProperty, BH
```suggestion
        [PreviousVersion("6.1", "BH.Engine.Structure.Create.Panel(BH.oM.Geometry.ICurve, System.Collections.Generic.List<BH.oM.Geometry.ICurve>, BH.oM.Structure.SurfaceProperties.ISurfaceProperty, BH.oM.Geometry.Vector, System.String)")]
```

2023-02-10 12:28 UTC, FraserGreenroyd commented on Structure_Engine/Create/Elements/Panel.cs
> +        [PreviousVersion("6.0", "BH.Engine.Structure.Create.Panel(System.Collections.Generic.List<BH.oM.Geometry.ICurve>, BH.oM.Structure.SurfaceProperties.ISurfaceProperty, BH.oM.Geometry.Vector, Sy
```suggestion
        [PreviousVersion("6.1", "BH.Engine.Structure.Create.Panel(System.Collections.Generic.List<BH.oM.Geometry.ICurve>, BH.oM.Structure.SurfaceProperties.ISurfaceProperty, BH.oM.Geometry.Vector, System.String)")]
```

2023-02-10 12:28 UTC, FraserGreenroyd commented on Structure_Engine/Create/Elements/Panel.cs
> +        [PreviousVersion("BH.Engine.Structure.Create.Panel(BH.oM.Geometry.PlanarSurface, BH.oM.Structure.SurfaceProperties.ISurfaceProperty, BH.oM.Geometry.Vector, System.String)")]
```suggestion
        [PreviousVersion("6.1", "BH.Engine.Structure.Create.Panel(BH.oM.Geometry.PlanarSurface, BH.oM.Structure.SurfaceProperties.ISurfaceProperty, BH.oM.Geometry.Vector, System.String)")]
```

2023-02-10 12:28 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-02-10 12:47 UTC, FraserGreenroyd commented
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check unit-tests

2023-02-10 15:29 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-02-10 15:46 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: null-handling

2023-02-10 15:46 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-02-10 15:48 UTC, FraserGreenroyd approved these changes
Code changes make sense, versioning is happy, happy to deploy following hack session.

2023-02-10 15:48 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-02-10 15:49 UTC, merged