Lighting_Engine: Algn to Luminaire oM Orientation Change
BHoM/BHoM_Engine pull request #3038
Opened 2023-04-12 17:31 UTC by enarhi

### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1501

   
### Issues addressed by this PR

Closes #3037 

Changed Luminaire and Transform methods to accommodate new Orientation property.

### Test files
[test files](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Lighting_Engine/Lighting_Engine-TestEngineMethods.gh?csf=1&web=1&e=VIvLXm)?csf=1&web=1&e=VIvLXm

### Changelog

### Additional comments

2023-04-12 17:33 UTC, enarhi commented
@BHoMBot check compliance

2023-04-12 17:36 UTC, enarhi commented
@BHoMBot check core

2023-04-12 17:38 UTC, enarhi commented
@BHoMBot check unit-tests
@BHoMBot check null-handling

2023-04-12 18:14 UTC, enarhi commented
@BHoMBot check unit-tests

2023-04-12 19:37 UTC, enarhi commented
@BHoMBot check compliance

2023-04-12 22:42 UTC, JohnSloane submitted a review, later dismissed
All appears to be working as expected. I tested this with the test files in rhino and gh to ensure all orientation is working appropriately with all engine methods.

2023-04-13 17:32 UTC, FraserGreenroyd requested changes

2023-04-13 17:32 UTC, FraserGreenroyd commented on Lighting_Engine/Create/Luminaire.cs
> +using ICSharpCode.Decompiler.IL.Transforms;
Why has this using been added?

2023-04-13 17:32 UTC, FraserGreenroyd commented on Lighting_Engine/Create/Luminaire.cs
> +                {
Why is this bit in its own brackets?

2023-04-13 18:11 UTC, enarhi commented on Lighting_Engine/Create/Luminaire.cs
> +                {
fixed

2023-04-13 18:11 UTC, enarhi commented on Lighting_Engine/Create/Luminaire.cs
> +using ICSharpCode.Decompiler.IL.Transforms;
removed

2023-04-13 18:12 UTC, enarhi commented
@BHoMBot check versioning

2023-04-13 18:16 UTC, enarhi commented
@BHoMBot check code-compliance
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

2023-04-13 18:31 UTC, enarhi commented
@BHoMBot check documentation-compliance

2023-04-13 21:11 UTC, FraserGreenroyd commented
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check unit-tests

2023-04-14 08:24 UTC, FraserGreenroyd approved these changes
Last commit only fixed my changes, functionality review from @JohnSloane still valid.

2023-04-14 08:45 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: dataset-compliance

2023-04-14 08:48 UTC, merged