Serializer_Enginge: IsValidJson checks if string is in valid format
BHoM/BHoM_Engine pull request #3097
Opened 2023-06-26 20:34 UTC by desaiwangBH

### Issues addressed by this PR

Closes #1427  

- checks if json is valid
- only checks if formatting is correct, does not validate schema

### Test files

### Changelog

### Additional comments

2023-06-28 13:45 UTC, FraserGreenroyd requested changes

2023-06-28 13:45 UTC, FraserGreenroyd commented on Serialiser_Engine/Query/Json.cs
> +
```suggestion
```

2023-06-28 13:45 UTC, FraserGreenroyd commented on Serialiser_Engine/Query/Json.cs
> +        [Input("string", "String to check.")]
```suggestion
        [Input("str", "String to check validity of.")]
```

2023-06-28 13:45 UTC, FraserGreenroyd commented on Serialiser_Engine/Query/Json.cs
> +        //JSON validation based on code from https://github.com/prototypejs/prototype/blob/560bb59414fc9343ce85429b91b1e1b82fdc6812/src/prototype/lang/string.js#L699
```suggestion
```

2023-06-28 13:45 UTC, FraserGreenroyd commented on Serialiser_Engine/Query/Json.cs
> +        {
```suggestion
        {
            //JSON validation based on code from https://github.com/prototypejs/prototype/blob/560bb59414fc9343ce85429b91b1e1b82fdc6812/src/prototype/lang/string.js#L699
```

2023-06-28 13:52 UTC, desaiwangBH commented on Serialiser_Engine/Query/Json.cs
> +        {
commas spelled wrong, I updated as suggested on my local branch and pushed to origin

2023-06-28 16:12 UTC, adecler reviewed
A few things from the top of my head that are not valid Json and yet are returning true:
 - `"A"`
 - `[{`
 - `[{:}{,}]`

2023-06-28 21:38 UTC, desaiwangBH commented
> A few things from the top of my head that are not valid Json and yet are returning true:
> 
> * `"A"`
> * `[{`
> * `[{:}{,}]`

@adecler 
According to [JsonLint](https://jsonlint.com/), `"A"` is a valid json. However, `A` would is not a valid json, but that is already returning false.

As for the rest of the cases, I realized that there was some issues with the regex. So instead I reverted the IsValidJson method logic back to using BSON, while adding a check that does return single values as valid ("A", true, null, 3, for example). However, I also noticed that BSON has some intelligence when parsing, so for [{\"name\": \"John\", city:"NYC"}] IsValidJson will return true even though city is not inside quotes/is not a string. 

I argue this is ok, since the `FromJson` also uses BSON methods, so all jsons that are determined to be valid can be parsed.

Also added unit tests. Let me know if there's anything else to do.

2023-07-03 20:15 UTC, FraserGreenroyd commented
Following offline discussion with @adecler and @desaiwangBH it has been agreed that this PR isn't needed anymore with the following reasons provided:

 - The Serialiser_Engine has come along a fair bit since January 2020 when #1427 was originally raised
 - The Adapters have likewise undergone improvement following work done by @alelom since January 2020
 - The JSON format used by BHoM, while needing to be valid JSON, also needs to be valid objects to deserialise to, as such `"A"`, while valid JSON, is not going to be able to be parsed by BHoM, so saying it is valid or invalid JSON doesn't help matters
 
Thanks @desaiwangBH for the research into the issue, we'll keep the code on these commits should we change our mind in the future, but as of today, this is the decision reached as a collective 😄

2023-07-03 20:15 UTC, closed without merging