Add new methods to Geometry_Engine & Bhom_Engine
BHoM/BHoM_Engine pull request #3102
Opened 2023-07-06 15:07 UTC by vietle-bh

### NOTE: This is #3035 reopened.

### Issues addressed by this PR

Closes #3033, Closes #3034

Added new methods such as:

-   Get the smallest possible angle between 2 vectors
-   Thickening a line into a polyline
-   Find line intersections between a polyline and a line
-   Find the distance between 2 points along a direction vector
-   Converting between degree and radian values
-   Copy property values between 2 objects where the property names match
-   Shifting and splitting a list

### Test files

### Changelog

Added engine methods for new use cases.

### Additional comments

2023-07-07 11:28 UTC, vietle-bh commented
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

2023-07-07 11:59 UTC, vietle-bh commented
@BHoMBot check unit-tests
@BHoMBot check versioning

2023-07-07 14:37 UTC, vietle-bh commented
@BHoMBot check unit-tests

2023-08-20 20:47 UTC, pawelbaran requested changes
I like the code, only a few minor tweaks suggested. However, please be so kind and provide a Grasshopper test script with the added methods - you are touching core projects of the entire BHoM here so extensive testing is a must. The script should ensure correctness of the methods as it will be serialised to serve as a unit test in the future.

2023-08-20 20:47 UTC, pawelbaran commented on BHoM_Engine/Modify/SplitAndRemoveAtIndexes.cs
> +        public static List<List<T>> SplitAndRemoveAtIndexes<T>(this List<T> items, List<int> indexes)
I would rather name the method as `RemoveAndSplitAtIndexes`

2023-08-20 20:47 UTC, pawelbaran commented on Geometry_Engine/Convert/ToXY.cs
> +    public static partial class Convert
This is definitely not a `Convert` method - a suitable method for this class takes an object of type A and converts it to an equivalent represented by type B. Instead, here we do a projection of `Point`, which definitely is `Modify`.

2023-08-20 20:47 UTC, pawelbaran commented on Geometry_Engine/Convert/ToXY.cs
> +        public static Point ToXY(this Point pnt)
I would rather call this method `ProjectToXY`

2023-08-23 16:28 UTC, vietle-bh commented
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

2023-08-24 10:27 UTC, vietle-bh commented
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

2023-08-24 10:36 UTC, vietle-bh commented
@BHoMBot check unit-tests

2023-08-24 10:53 UTC, vietle-bh commented
@pawelbaran , I've added the GH test script to this PR's description.

2023-08-24 17:27 UTC, pawelbaran commented
@vietle-bh I have had a look at the test script you prepared - it is a good start, but definitely not sufficient (not enough cases, no verification). I quickly patched up an alternative how I would do it and uploaded it [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233102%2DAddTaggingTool&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4). Let's have a chat tomorrow to coordinate on how to bring this PR over the line 💪

2023-08-25 11:20 UTC, pawelbaran commented
@BHoMBot check unit-tests

2023-08-25 12:01 UTC, pawelbaran approved these changes
Happy to approve the PR following the code review, testing and unit test creation done together with @vietle-bh 👍 Good stuff!

2023-08-25 13:01 UTC, vietle-bh commented
@BHoMBot check required

2023-08-25 14:06 UTC, vietle-bh commented
@BHoMBot check versioning

2023-08-25 15:17 UTC, vietle-bh commented
Sorry @FraserGreenroyd , similar story here where the failed test isn't relevant to this PR. It's the unit-tests this time. Could we bypass this please?

2023-08-28 10:40 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-08-28 10:43 UTC, FraserGreenroyd commented
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

2023-08-28 10:46 UTC, FraserGreenroyd commented
@BHoMBot check versioning
@BHoMBot check installer

2023-08-28 11:25 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge, unit-tests

2023-08-28 11:25 UTC, merged